Repository ralna/GALAHAD, pull requests merged in 2025-07, with the labels that each got.

#429 [GALAHAD.jl] Update the interface for run_sif and run_qplib
  GALAHAD.jl/gen/wrapper.jl
  GALAHAD.jl/src/GALAHAD.jl
  GALAHAD.jl/src/utils.jl
  GALAHAD.jl/src/wrappers/arc.jl
  GALAHAD.jl/src/wrappers/bgo.jl
  GALAHAD.jl/src/wrappers/blls.jl
  GALAHAD.jl/src/wrappers/bllsb.jl
  GALAHAD.jl/src/wrappers/bnls.jl
  GALAHAD.jl/src/wrappers/bqp.jl
  GALAHAD.jl/src/wrappers/bqpb.jl
  GALAHAD.jl/src/wrappers/ccqp.jl
  GALAHAD.jl/src/wrappers/cdqp.jl
  GALAHAD.jl/src/wrappers/clls.jl
  GALAHAD.jl/src/wrappers/cqp.jl
  GALAHAD.jl/src/wrappers/demo.jl
  GALAHAD.jl/src/wrappers/dgo.jl
  GALAHAD.jl/src/wrappers/dlp.jl
  GALAHAD.jl/src/wrappers/dps.jl
  GALAHAD.jl/src/wrappers/dqp.jl
  GALAHAD.jl/src/wrappers/eqp.jl
  GALAHAD.jl/src/wrappers/expo.jl
  GALAHAD.jl/src/wrappers/fdh.jl
  GALAHAD.jl/src/wrappers/filtrane.jl
  GALAHAD.jl/src/wrappers/glrt.jl
  GALAHAD.jl/src/wrappers/gltr.jl
  GALAHAD.jl/src/wrappers/l1qp.jl
  GALAHAD.jl/src/wrappers/l2rt.jl
  GALAHAD.jl/src/wrappers/lancelot.jl
  GALAHAD.jl/src/wrappers/lls.jl
  GALAHAD.jl/src/wrappers/lpa.jl
  GALAHAD.jl/src/wrappers/lpb.jl
  GALAHAD.jl/src/wrappers/lpqp.jl
  GALAHAD.jl/src/wrappers/lqr.jl
  GALAHAD.jl/src/wrappers/lqt.jl
  GALAHAD.jl/src/wrappers/lsrt.jl
  GALAHAD.jl/src/wrappers/lstr.jl
  GALAHAD.jl/src/wrappers/miqr.jl
  GALAHAD.jl/src/wrappers/nls.jl
  GALAHAD.jl/src/wrappers/nodend.jl
  GALAHAD.jl/src/wrappers/presolve.jl
  GALAHAD.jl/src/wrappers/qp.jl
  GALAHAD.jl/src/wrappers/qpa.jl
  GALAHAD.jl/src/wrappers/qpb.jl
  GALAHAD.jl/src/wrappers/qpc.jl
  GALAHAD.jl/src/wrappers/rqs.jl
  GALAHAD.jl/src/wrappers/sbls.jl
  GALAHAD.jl/src/wrappers/sha.jl
  GALAHAD.jl/src/wrappers/sils.jl
  GALAHAD.jl/src/wrappers/slls.jl
  GALAHAD.jl/src/wrappers/sls.jl
  GALAHAD.jl/src/wrappers/trb.jl
  GALAHAD.jl/src/wrappers/trs.jl
  GALAHAD.jl/src/wrappers/tru.jl
  GALAHAD.jl/src/wrappers/ugo.jl
  GALAHAD.jl/src/wrappers/warm.jl
  GALAHAD.jl/src/wrappers/wcp.jl
  src/expo/Julia/expo.jl
Labels: enhancement

#432 [GALAHAD.jl] Use the linear solvers of LAPACK for unit tests
  GALAHAD.jl/test/test_arc.jl
  GALAHAD.jl/test/test_blls.jl
  GALAHAD.jl/test/test_bllsb.jl
  GALAHAD.jl/test/test_bqpb.jl
  GALAHAD.jl/test/test_ccqp.jl
  GALAHAD.jl/test/test_clls.jl
  GALAHAD.jl/test/test_cqp.jl
  GALAHAD.jl/test/test_dgo.jl
  GALAHAD.jl/test/test_dps.jl
  GALAHAD.jl/test/test_dqp.jl
  GALAHAD.jl/test/test_eqp.jl
  GALAHAD.jl/test/test_fdc.jl
  GALAHAD.jl/test/test_l2rt.jl
  GALAHAD.jl/test/test_llsr.jl
  GALAHAD.jl/test/test_llst.jl
  GALAHAD.jl/test/test_lpb.jl
  GALAHAD.jl/test/test_lsqp.jl
  GALAHAD.jl/test/test_nls.jl
  GALAHAD.jl/test/test_psls.jl
  GALAHAD.jl/test/test_qpa.jl
  GALAHAD.jl/test/test_qpb.jl
  GALAHAD.jl/test/test_rqs.jl
  GALAHAD.jl/test/test_sbls.jl
  GALAHAD.jl/test/test_slls.jl
  GALAHAD.jl/test/test_trb.jl
  GALAHAD.jl/test/test_trs.jl
  GALAHAD.jl/test/test_tru.jl
  GALAHAD.jl/test/test_wcp.jl
Labels: julia

#459 [CI] Build python wheels on version tags
  .github/workflows/build_wheels.yml
Labels: CI

#461 [CI] Use the Intel compilers again
  .github/meson/action.yml
  .github/workflows/meson.yml
  meson.build
  src/forthcoming/expo/useexpo.F90
Labels: CI
